[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "cp package.prod.json package.json",
  "cp package-lock.prod.json package-lock.json",
  "npm ci",
  "npm run build"
]

[start]
cmd = "npm start"

