[build]
builder = "NIXPACKS"
buildCommand = "cp package.prod.json package.json && cp package-lock.prod.json package-lock.json && npm ci && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

