"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ENV_VARS = void 0;
// Environment variable names
exports.ENV_VARS = {
    MOCK_ENABLED: 'MOCKIFYER_ENABLED',
    MOCK_RECORD: 'MOCKIFYER_RECORD',
    MOCK_PATH: 'MOCKIFYER_PATH',
    MOCK_SCENARIO: 'MOCKIFYER_SCENARIO',
    MOCK_DATE: 'MOCKIFYER_DATE',
    MOCK_DATE_OFFSET: 'MOCKIFYER_DATE_OFFSET',
    MOCK_TIMEZONE: 'MOCKIFYER_TIMEZONE',
    MOCK_USE_SIMILAR_MATCH: 'MOCKIFYER_USE_SIMILAR_MATCH',
    MOCK_USE_SIMILAR_MATCH_CHECK_RESPONSE: 'MOCKIFYER_USE_SIMILAR_MATCH_CHECK_RESPONSE'
};
